name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set-up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck make
      - name: Validate shell code formatting
        run: make lint
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set-up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen make
      - name: Build the doc
        run: make doc
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set-up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen shellcheck make
      - name: Full build
        run: make
